import json

rekap_pesanan = {
    "order_jam_tangan": [
        {
            "order_id": "14264504",
            "product": " (Hitam - Orange) (x1)",
            "name": "Dendi indrayadi alfiansah",
            "phone": "6.28953E+13",
            "address": "Jl. Flamboyan 3 no 319 rt 08 rw 010 kel: jakasampurna,perumnas 1 bekasi",
            "province": "Jawa Barat",
            "city": "Kota Bekasi",
            "subdistrict": "Bekasi Barat",
            "zip": "17134",
            "product_price": "243000"
        },
        {
            "order_id": "14445620",
            "product": " (Hitam - Orange) (x1)",
            "name": "Fadli",
            "phone": "6.28577E+12",
            "address": "Sinar Mas Land Plaza BSD City, Jl. BSD Green Office Park Jl. BSD Grand Boulevard, Sampora, Kec. Cisauk, Tangerang, Banten 15345",
            "province": "Banten",
            "city": "Kab. Tangerang",
            "subdistrict": "Cisauk",
            "zip": "15344",
            "product_price": "243000"
        },
        {
            "order_id": "14620893",
            "product": " (Hitam - Orange) (x1)",
            "name": "Jajat sudrajat",
            "phone": "6.28381E+12",
            "address": "Kp.kp.pasir rt05/rw03 ds.pasir kec.kronjo kab.tangerang  depan depot air minum mang sapi",
            "province": "Banten",
            "city": "Kab. Tangerang",
            "subdistrict": "Kronjo",
            "zip": "15550",
            "product_price": "243000"
        },
        {
            "order_id": "14623921",
            "product": " (Hitam - Orange) (x1)",
            "name": "M. EWIN SURYA R.N",
            "phone": "6.28116E+11",
            "address": "PT. LAMBANG JAYA JL. RAYA HAJI MENA KM. 14 NO.165 NATAR - LAMPUNG SELATAN",
            "province": "Lampung",
            "city": "Kab. Lampung Utara",
            "subdistrict": "Abung Barat",
            "zip": "34558",
            "product_price": "243000"
        },
        {
            "order_id": "14624207",
            "product": " (Hitam - Orange) (x1)",
            "name": "Soleha",
            "phone": "6.28218E+12",
            "address": "Bengkel aljupri jalan poros pasar desa danau",
            "province": "Jambi",
            "city": "Kab. Bungo",
            "subdistrict": "Pelepat Ilir",
            "zip": "37252",
            "product_price": "243000"
        },
        {
            "order_id": "14624270",
            "product": " (Hitam - Orange) (x1)",
            "name": "Danny H",
            "phone": "6.28582E+12",
            "address": "Jl. Camar VII Blok AM No.4 RT/RW 006/008, Bintaro Jaya , Sektor 3.",
            "province": "Banten",
            "city": "Kota Tangerang Selatan",
            "subdistrict": "Pondok Aren",
            "zip": "15223",
            "product_price": "243000"
        },
        {
            "order_id": "14624572",
            "product": " (Hitam - Orange) (x1)",
            "name": "Imam fidianto",
            "phone": "6.28522E+12",
            "address": "Asmil Yon Mandala yudha",
            "province": "Banten",
            "city": "Kab. Lebak",
            "subdistrict": "Sajira",
            "zip": "42371",
            "product_price": "243000"
        },
        {
            "order_id": "14624718",
            "product": " (Hitam - Orange) (x1)",
            "name": "Khairil Anwar",
            "phone": "6.28539E+12",
            "address": "Dusun 1,Desa Kondara.Kec,Pakue.Kab,Kolaka Utara",
            "province": "Sulawesi Tenggara",
            "city": "Kab. Kolaka Utara",
            "subdistrict": "Pakue",
            "zip": "93954",
            "product_price": "243000"
        },
        {
            "order_id": "14628368",
            "product": " (Hitam - Orange) (x1)",
            "name": "Achmad Sunaryo",
            "phone": "6.2823E+12",
            "address": "Jl.R.Abd Azis 21 Pamekasan Madura",
            "province": "Jawa Timur",
            "city": "Kab. Pamekasan",
            "subdistrict": "Pamekasan",
            "zip": "69317",
            "product_price": "243000"
        },
        {
            "order_id": "14629836",
            "product": " (Hitam - Orange) (x1)",
            "name": "Supriatna",
            "phone": "6.28566E+12",
            "address": "Perumahan Taman kuta Bumi 2 Jl.Jambrut 1 Blok B.11 No.12 Rt.002 Rw.021 kel.Kuta Bumi Kec.Pasar Kemis Kabupaten Tangerang.",
            "province": "Banten",
            "city": "Kab. Tangerang",
            "subdistrict": "Pasar Kemis",
            "zip": "15560",
            "product_price": "243000"
        },
        {
            "order_id": "14630679",
            "product": " (Hitam - Orange) (x1)",
            "name": "Roy",
            "phone": "6.28162E+11",
            "address": "Taman Cipulir estate Jl. cendana  I blok A1/6",
            "province": "Banten",
            "city": "Kota Tangerang",
            "subdistrict": "Larangan",
            "zip": "15155",
            "product_price": "243000"
        },
        {
            "order_id": "14630792",
            "product": " (Hitam - Orange) (x1)",
            "name": "Antonio agustio",
            "phone": "6.2896E+12",
            "address": "Blok IV Dukuh pari Ds.Leuwiseeng kec.panyingkiran Kab.MAJALENGKA",
            "province": "Jawa Barat",
            "city": "Kab. Majalengka",
            "subdistrict": "Panyingkiran",
            "zip": "45459",
            "product_price": "243000"
        },
        {
            "order_id": "14632105",
            "product": " (Hitam - Orange) (x1)",
            "name": "Willy",
            "phone": "6.28228E+12",
            "address": "Kav.sei lekop blok D no 351, kelurahan sei lekop",
            "province": "Kepulauan Riau",
            "city": "Kota Batam",
            "subdistrict": "Sagulung",
            "zip": "29439",
            "product_price": "243000"
        },
        {
            "order_id": "14632585",
            "product": " (Hitam - Orange) (x1)",
            "name": "Hafidh Ghany N.S",
            "phone": "6.2819E+12",
            "address": "Jumoyo kidul, Rt 03 Rw 02, Jumoyo, Salam",
            "province": "Jawa Tengah",
            "city": "Kab. Magelang",
            "subdistrict": "Salam",
            "zip": "56484",
            "product_price": "243000"
        },
        {
            "order_id": "14633133",
            "product": " (Hitam - Orange) (x1)",
            "name": "Wawan Syah",
            "phone": "6.28127E+12",
            "address": "Jalan kesatrian , asrama AD NO 39 an Wawan syah",
            "province": "Jawa Tengah",
            "city": "Kab. Banyumas",
            "subdistrict": "Purwokerto Timur",
            "zip": "53113",
            "product_price": "243000"
        },
        {
            "order_id": "14634912",
            "product": " (Hitam - Orange) (x1)",
            "name": "Nurdin Saleh",
            "phone": "6.28132E+12",
            "address": "PT Super Unggas Jaya (Suja) Dsn. Cijambe RT 001 RW 05 Ds. Cibatu Ireng Kec. Karangnunggal Kab. Tasikmalaya",
            "province": "Jawa Barat",
            "city": "Kab. Tasikmalaya",
            "subdistrict": "Karangnunggal",
            "zip": "46186",
            "product_price": "243000"
        },
        {
            "order_id": "14635334",
            "product": " (Hitam - Orange) (x1)",
            "name": "Boni Gainau",
            "phone": "6.28522E+12",
            "address": "Paldam V/BrawijayaJalan Mulyorejo Indah no.12 Surabaya Timur",
            "province": "Jawa Timur",
            "city": "Kota Surabaya",
            "subdistrict": "Mulyorejo",
            "zip": "60113",
            "product_price": "243000"
        },
        {
            "order_id": "14635698",
            "product": " (Hitam - Orange) (x1)",
            "name": "Andi jais",
            "phone": "6.28219E+12",
            "address": "Aspol brimob lemboroma. Jln trans sulawesi km12 kec lembo.kab morowali utara",
            "province": "Sulawesi Tengah",
            "city": "Kab. Morowali",
            "subdistrict": "Lembo",
            "zip": "94966",
            "product_price": "243000"
        },
        {
            "order_id": "14637843",
            "product": " (Hitam - Orange) (x1)",
            "name": "Lusianto LP",
            "phone": "6.28113E+11",
            "address": "Jl. Transisi no.44 RT.01 RW.03 Kelurahan Ngelo",
            "province": "Jawa Tengah",
            "city": "Kab. Blora",
            "subdistrict": "Cepu",
            "zip": "58311",
            "product_price": "243000"
        },
        {
            "order_id": "14640800",
            "product": " (Hitam - Orange) (x1)",
            "name": "Aries s",
            "phone": "6.28575E+12",
            "address": "JL Raden Patah 2 /32b RT 11RW 03 Pekauman Sidoarjo kodepost 61213 Kabupaten S",
            "province": "Jawa Timur",
            "city": "Kab. Sidoarjo",
            "subdistrict": "Balongbendo",
            "zip": "61263",
            "product_price": "243000"
        },
        {
            "order_id": "14641237",
            "product": " (Hitam - Orange) (x1)",
            "name": "Mamah kayla",
            "phone": "6.28381E+12",
            "address": "Jl.kavling Pratama 1 GG.tuna rt010/05 no.30 Kel:Rorotan kec:Cilincing Jakarta Utara 14140",
            "province": "DKI Jakarta",
            "city": "Kota Jakarta Utara",
            "subdistrict": "Cilincing",
            "zip": "14120",
            "product_price": "243000"
        },
        {
            "order_id": "14642200",
            "product": " (Hitam - Orange) (x1)",
            "name": "Ilham suhendar",
            "phone": "6.28521E+12",
            "address": "Jl.RE.MARTADHINATA NO 63-65",
            "province": "Jawa Barat",
            "city": "Kota Sukabumi",
            "subdistrict": "Cikole",
            "zip": "43113",
            "product_price": "243000"
        },
        {
            "order_id": "14643925",
            "product": " (Hitam - Orange) (x1)",
            "name": "Rizky",
            "phone": "6.28588E+12",
            "address": "Kp cibadak rt 02/04,alas wangi menes pandglang banten",
            "province": "Banten",
            "city": "Kab. Pandeglang",
            "subdistrict": "Menes",
            "zip": "42262",
            "product_price": "243000"
        },
        {
            "order_id": "14645737",
            "product": " (Hitam - Orange) (x1)",
            "name": "Firman Maulana",
            "phone": "6.28782E+12",
            "address": "Jl.kebagusan wates gg.peon rt.02/rw.04 no.54 (belakang warung buah peon H.napih) kel.kebagusan kec.pasar minggu jaksel 12520",
            "province": "DKI Jakarta",
            "city": "Kota Jakarta Selatan",
            "subdistrict": "Pasar Minggu",
            "zip": "12560",
            "product_price": "243000"
        },
        {
            "order_id": "14646845",
            "product": " (Hitam - Orange) (x1)",
            "name": "Jefry kusnawan",
            "phone": "6.28581E+12",
            "address": "Jl.diponegoro kp.kedung gede Rt001/03 Ds.jatimulya kec.Tambun Selatan Kab.Bekasi (Samping Pt.Suzuki indomobil Plant 2 Tambun)",
            "province": "Jawa Barat",
            "city": "Kab. Bekasi",
            "subdistrict": "Tambun Selatan",
            "zip": "17510",
            "product_price": "243000"
        },
        {
            "order_id": "14647297",
            "product": " (Hitam - Orange) (x1)",
            "name": "RISCO SIRAIT",
            "phone": "6.28529E+12",
            "address": "Jln.RE Martadinata Komplek Bina Marga BPJN XXII  Merauke Kab.Merauﾄｷe",
            "province": "Papua",
            "city": "Kab. Merauke",
            "subdistrict": "Animha",
            "zip": "99656",
            "product_price": "243000"
        },
        {
            "order_id": "14648011",
            "product": " (Hitam - Orange) (x2) (Hitam - Biru Tua) (x1)",
            "name": "Farhad/Amy",
            "phone": "6.28219E+12",
            "address": "Jalan hegarmanah Kulon RT 07 RW 08 Gg. Ranim 47. Kel Hegarmanah, Kec Cidadap. Kota Bandung 40141",
            "province": "Jawa Barat",
            "city": "Kota Bandung",
            "subdistrict": "Cidadap",
            "zip": "40142",
            "product_price": "486000"
        },
        {
            "order_id": "14649188",
            "product": " (Hitam - Orange) (x2)",
            "name": "Setiyono.S",
            "phone": "6.28154E+12",
            "address": "Ds.Bantarwuni RT 01 RW 02 Kec.Kembaran Kab.Banyumas",
            "province": "Jawa Tengah",
            "city": "Kab. Banyumas",
            "subdistrict": "Kembaran",
            "zip": "53182",
            "product_price": "243000"
        },
        {
            "order_id": "14650704",
            "product": " (Hitam - Orange) (x2)",
            "name": "Lasminto",
            "phone": "6.28215E+12",
            "address": "Bataliyon arhanud 12/sbp jln Palembang Betung km 18 Sukomoro kec talang kelapa kab Banyuasin Sumatra Selatan",
            "province": "Sumatera Selatan",
            "city": "Kota Palembang",
            "subdistrict": "Alang-Alang Lebar",
            "zip": "30154",
            "product_price": "243000"
        },
        {
            "order_id": "14654843",
            "product": " (Hitam - Orange) (x2)",
            "name": "Nico",
            "phone": "6.28212E+12",
            "address": "Apartemen East Park Tower A Unit AC.02 No.2, Jl. DR. KRT.  Radjiman Widyodiningrat, Kel. Jatinegara, Kec. Cakung, Jakarta Timur.",
            "province": "DKI Jakarta",
            "city": "Kota Jakarta Timur",
            "subdistrict": "Cakung",
            "zip": "13910",
            "product_price": "243000"
        },
        {
            "order_id": "14661868",
            "product": " (Hitam - Biru Tua) (x1) (Hitam - Biru Tua) (x1)",
            "name": "Yanto",
            "phone": "6.28128E+12",
            "address": "Yanto  alamat slagi rtbo7 rw 02",
            "province": "Jawa Tengah",
            "city": "Kab. Jepara",
            "subdistrict": "Pakis Aji",
            "zip": "59452",
            "product_price": "729000"
        },
        {
            "order_id": "14662363",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Aseng Pakisaji",
            "phone": "6.28128E+12",
            "address": "Slgi",
            "province": "Jawa Tengah",
            "city": "Kab. Jepara",
            "subdistrict": "Pakis Aji",
            "zip": "59452",
            "product_price": "243000"
        },
        {
            "order_id": "14663400",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Hendri tanjung",
            "phone": "62811246378",
            "address": "Jln.suryalaya asri I.nomor:3.Buah batu-rt:10rw:04.kota bandung",
            "province": "Jawa Barat",
            "city": "Kota Bandung",
            "subdistrict": "Batununggal",
            "zip": "40275",
            "product_price": "243000"
        },
        {
            "order_id": "14666796",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Aan handayani",
            "phone": "6.28777E+12",
            "address": "Jln.ahmad yani km2 kp.pasir malang rt02/03 kaduagung timur.cibadak.lebak 34218",
            "province": "Banten",
            "city": "Kab. Lebak",
            "subdistrict": "Cibadak",
            "zip": "42357",
            "product_price": "243000"
        },
        {
            "order_id": "14668045",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Helmy ria suryawan",
            "phone": "6.28123E+12",
            "address": "Green menganti b3 no9 RT.16/RW08 MENGANTI-GRESIK",
            "province": "Jawa Timur",
            "city": "Kab. Gresik",
            "subdistrict": "Menganti",
            "zip": "61174",
            "product_price": "243000"
        },
        {
            "order_id": "14670829",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Muhammad Dzulfachri",
            "phone": "6.28131E+12",
            "address": "Jl. Bintara No.73, RT.005/RW.005, Bintara, Kec. Bekasi Bar., Kota Bks, Jawa Barat 17136",
            "province": "Jawa Barat",
            "city": "Kota Bekasi",
            "subdistrict": "Bekasi Barat",
            "zip": "17134",
            "product_price": "243000"
        },
        {
            "order_id": "14695487",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Dadi aa",
            "phone": "6.2857E+11",
            "address": "Klinik bidan fatma, jl. Gatot subroto km. Dekat hermina bitung tangerang. Kp pos bitung rt. 01/04 no.45. kadu curug tangerng 15810",
            "province": "Banten",
            "city": "Kab. Tangerang",
            "subdistrict": "Curug",
            "zip": "15810",
            "product_price": "243000"
        },
        {
            "order_id": "14696446",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Santi susanti",
            "phone": "6.28579E+12",
            "address": "Perum the orange ko.citengah RT.02 RW.02 desa Sukamulya kecamatan cikembar kab.sukabumi",
            "province": "Jawa Barat",
            "city": "Kab. Sukabumi",
            "subdistrict": "Cikembar",
            "zip": "43157",
            "product_price": "243000"
        },
        {
            "order_id": "14698327",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Nugroho Agung",
            "phone": "6.28134E+12",
            "address": "Kaliwanglu kulon rt 001 rw 017 ds. Harjobinangun kec. Pakem kab. Sleman",
            "province": "DI Yogyakarta",
            "city": "Kab. Sleman",
            "subdistrict": "Pakem",
            "zip": "55582",
            "product_price": "243000"
        },
        {
            "order_id": "14702964",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Budi ambon",
            "phone": "6.2813E+12",
            "address": "Kp baru sampora rt 001/04 no 10 desa sampora kec cisauk kab tangerang",
            "province": "Banten",
            "city": "Kab. Tangerang",
            "subdistrict": "Cisauk",
            "zip": "15344",
            "product_price": "243000"
        },
        {
            "order_id": "14703783",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Wasis abadi",
            "phone": "6.28139E+12",
            "address": "Jl.anggrek 1 no.7 griya abdi kencana",
            "province": "Jawa Tengah",
            "city": "Kab. Purbalingga",
            "subdistrict": "Purbalingga",
            "zip": "53316",
            "product_price": "243000"
        },
        {
            "order_id": "14705843",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Eka Afrianto",
            "phone": "6.28229E+12",
            "address": "Sumbar. Kab.solok. kec.lembah Gumanti. Nagari sungai nanam. Jorong Padang Laweh. Simpang mesjid Padang laweh",
            "province": "Sumatera Barat",
            "city": "Kab. Solok",
            "subdistrict": "Lembah Gumanti",
            "zip": "27371",
            "product_price": "243000"
        },
        {
            "order_id": "14706739",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Paul",
            "phone": "6.28593E+12",
            "address": "Perum Bukit Gading Residen Blok C5 No 3 Cengkong",
            "province": "Jawa Barat",
            "city": "Kab. Karawang",
            "subdistrict": "Klari",
            "zip": "41371",
            "product_price": "243000"
        },
        {
            "order_id": "14707751",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Zemi",
            "phone": "6.2823E+12",
            "address": "Perumahan Serpong Natura City . Cluster Catelya NC2. 7 Pengasinan . gunung sindur  Parung . BOGOR",
            "province": "Jawa Barat",
            "city": "Kab. Bogor",
            "subdistrict": "Gunung Sindur",
            "zip": "16340",
            "product_price": "295000"
        },
        {
            "order_id": "14708437",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "cian lin",
            "phone": "6.28124E+12",
            "address": "TAMANA PALEM LESTARI, RUKO 1000 PELANGI BLOK F 25, JAKARTA BARAT",
            "province": "DKI Jakarta",
            "city": "Kota Jakarta Barat",
            "subdistrict": "Cengkareng",
            "zip": "11730",
            "product_price": "295000"
        },
        {
            "order_id": "14709666",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "inda manuel",
            "phone": "6.28132E+12",
            "address": "komplek sacna  jl.nusantara 2 blok G14 sunter jakarta utara",
            "province": "DKI Jakarta",
            "city": "Kota Jakarta Utara",
            "subdistrict": "Tanjung Priok",
            "zip": "14320",
            "product_price": "295000"
        },
        {
            "order_id": "14718441",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Sekhnudin",
            "phone": "6.28227E+12",
            "address": "Jl arsad rt 2 rw 5 no 3 desa kertasari",
            "province": "Jawa Tengah",
            "city": "Kab. Tegal",
            "subdistrict": "Surodadi",
            "zip": "52182",
            "product_price": "295000"
        },
        {
            "order_id": "14720214",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Cecep kurniawan",
            "phone": "6.28128E+12",
            "address": "Kp.Bendungan Melayu RT.004 RW.002 No.53 Kelurahan. Rawa Badak Selatan kecamatan. Koja Jakarta utara",
            "province": "DKI Jakarta",
            "city": "Kota Jakarta Utara",
            "subdistrict": "Koja",
            "zip": "14210",
            "product_price": "295000"
        },
        {
            "order_id": "14725635",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Budi",
            "phone": "6.28564E+12",
            "address": "Kampung rawa lindung rt.11 rw.06 Kelurahan cengklong Kec.Kosambi",
            "province": "Banten",
            "city": "Kab. Tangerang",
            "subdistrict": "Kosambi",
            "zip": "15212",
            "product_price": "295000"
        },
        {
            "order_id": "14745001",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Ahmad Yaskur",
            "phone": "6.28135E+12",
            "address": "Jalan Kalijudan gg8 Nomor 10A",
            "province": "Jawa Timur",
            "city": "Kota Surabaya",
            "subdistrict": "Mulyorejo",
            "zip": "60113",
            "product_price": "295000"
        },
        {
            "order_id": "14751238",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Rico steven",
            "phone": "6.28133E+12",
            "address": "Jalan cendrawasih no 87",
            "province": "Papua Barat",
            "city": "Kab. Manokwari",
            "subdistrict": "Manokwari Barat",
            "zip": "98314",
            "product_price": "295000"
        },
        {
            "order_id": "14752983",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "abdulloh",
            "phone": "6.28128E+11",
            "address": "jl.p.komarudin rt14 rw05 kel.pulo gebang. kec.cakung. jaktim no.rmh.131",
            "province": "DKI Jakarta",
            "city": "Kota Jakarta Timur",
            "subdistrict": "Cakung",
            "zip": "13910",
            "product_price": "295000"
        },
        {
            "order_id": "14758166",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "handoyo hadi",
            "phone": "62811428000",
            "address": "delatinos bahamas resort blok a2/12 bsd tangerang selatan",
            "province": "Banten",
            "city": "Kab. Tangerang",
            "subdistrict": "Balaraja",
            "zip": "15610",
            "product_price": "295000"
        },
        {
            "order_id": "14758444",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Rudi yanto",
            "phone": "6.28212E+12",
            "address": "Jln cilengkrang 1 no 146 rt04/05 Desa cisurupan",
            "province": "Jawa Barat",
            "city": "Kota Bandung",
            "subdistrict": "Andir",
            "zip": "40184",
            "product_price": "295000"
        },
        {
            "order_id": "14763547",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Catur",
            "phone": "6.28211E+12",
            "address": "Komp Cakrawala 2 Blok L5,rt04 rw15 jatirangga kec jatisampurna Bekasi Jawa barat",
            "province": "Jawa Barat",
            "city": "Kota Bekasi",
            "subdistrict": "Jati Sampurna",
            "zip": "17435",
            "product_price": "295000"
        },
        {
            "order_id": "14763839",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Catur",
            "phone": "6.28211E+12",
            "address": "Komp Cakrawala 2 blok L5,rt04 rw15 jatirangga kec jatisampurna bekasi",
            "province": "Jawa Barat",
            "city": "Kota Bekasi",
            "subdistrict": "Jati Sampurna",
            "zip": "17435",
            "product_price": "295000"
        },
        {
            "order_id": "14765230",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Beni Rangkuti",
            "phone": "6.28123E+12",
            "address": "Jl mawar II no 22a rt 2 rw 14 kelurahan bintaro kec pesanggrahan Jakarta selayan",
            "province": "DKI Jakarta",
            "city": "Kota Jakarta Selatan",
            "subdistrict": "Pesanggrahan",
            "zip": "12330",
            "product_price": "295000"
        },
        {
            "order_id": "14765606",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "MURSALIM ALIM",
            "phone": "6.28125E+12",
            "address": "Bataliyon howitzer 2 marinir",
            "province": "Jawa Timur",
            "city": "Kota Surabaya",
            "subdistrict": "Asemrowo",
            "zip": "60182",
            "product_price": "295000"
        },
        {
            "order_id": "14770958",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Nama",
            "phone": "6.28542E+14",
            "address": "Perum sidokare indah NN.4",
            "province": "Jawa Timur",
            "city": "Kab. Sidoarjo",
            "subdistrict": "Candi",
            "zip": "61271",
            "product_price": "295000"
        },
        {
            "order_id": "14777861",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Helmi Sungkar",
            "phone": "6.2853E+12",
            "address": "Nama lengkap :  Helmi Sungkar Alamat :  Perumahan Citra 1 extension, blok AC 3 No.1, RT 006  RW 015, kalideres Jakarta Barat Provinsi: Jakarta Kota/Kab.: Jakart",
            "province": "DKI Jakarta",
            "city": "Kota Jakarta Barat",
            "subdistrict": "Kalideres",
            "zip": "11840",
            "product_price": "295000"
        },
        {
            "order_id": "14779336",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Edi moerseno",
            "phone": "6.28123E+11",
            "address": "Jl.plamongan asri barat no.7 semarang",
            "province": "Jawa Tengah",
            "city": "Kota Semarang",
            "subdistrict": "Pedurungan",
            "zip": "50246",
            "product_price": "295000"
        },
        {
            "order_id": "14782517",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Teguh Sutrisno",
            "phone": "6.28523E+12",
            "address": "Dsn juworo rt 07 rw 01 Ds Karangrejo kec gabus kab Grobogan Jawa tengah",
            "province": "Jawa Tengah",
            "city": "Kab. Grobogan",
            "subdistrict": "Gabus",
            "zip": "58183",
            "product_price": "295000"
        },
        {
            "order_id": "14784832",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Herman Damsuri",
            "phone": "6.2857E+12",
            "address": "Perum TNI AD Puspa Raya blok DF 34 RT 004/011 Bojong Baru Bojong Gede Bogor",
            "province": "Jawa Barat",
            "city": "Kab. Bogor",
            "subdistrict": "Bojonggede",
            "zip": "16920",
            "product_price": "295000"
        },
        {
            "order_id": "14788808",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Ifahadi",
            "phone": "6.28128E+12",
            "address": "Jl. Delima II blok A no 29 Rt /Rw 02/12 perum duren jaya",
            "province": "Jawa Barat",
            "city": "Kota Bekasi",
            "subdistrict": "Bekasi Timur",
            "zip": "17111",
            "product_price": "295000"
        },
        {
            "order_id": "14789735",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "kiki",
            "phone": "62856987653",
            "address": "cianjur",
            "province": "Jawa Barat",
            "city": "Kab. Cianjur",
            "subdistrict": "Agrabinta",
            "zip": "43273",
            "product_price": "295000"
        },
        {
            "order_id": "14793526",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Budiman",
            "phone": "6.28136E+12",
            "address": "Jl. Bacang No. 26 RT. 04 RW. 07 Kel. Rawasari Kec. Cempaka Putih Jakarta Pusat",
            "province": "DKI Jakarta",
            "city": "Kota Jakarta Pusat",
            "subdistrict": "Cempaka Putih",
            "zip": "10520",
            "product_price": "295000"
        },
        {
            "order_id": "14798598",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Saepudin",
            "phone": "6.28191E+12",
            "address": "Komplek TNI AD Jl. Durian Raya Blok F 6 No. 18 RT. 001/011 Kel.  Sukamaju Baru - Tapos - Depok",
            "province": "Jawa Barat",
            "city": "Kota Depok",
            "subdistrict": "Tapos",
            "zip": "16458",
            "product_price": "295000"
        },
        {
            "order_id": "14798686",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Nanang Fachrurruzi",
            "phone": "6.28239E+12",
            "address": "Jln. Gunung merapi gg. Cemara angin bumi ayu no. 1",
            "province": "Riau",
            "city": "Kota Dumai",
            "subdistrict": "Dumai Selatan",
            "zip": "28825",
            "product_price": "295000"
        },
        {
            "order_id": "14801552",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Okto Lut",
            "phone": "6.28115E+11",
            "address": "Asrama Rindam XVII/Cenderawasih Jln. Pojok Ifargunung. Kec. Sentani Kota Kab. Jayapura Prov. Papua",
            "province": "Papua",
            "city": "Kab. Jayapura",
            "subdistrict": "Sentani",
            "zip": "99352",
            "product_price": "295000"
        },
        {
            "order_id": "14802589",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "daniel fitriansyah",
            "phone": "6.28527E+12",
            "address": "Jln. A. Yani Km. 4,5 Komplek Aspol Bina Brata Blok A No. 14",
            "province": "Kalimantan Selatan",
            "city": "Kota Banjarmasin",
            "subdistrict": "Banjarmasin Timur",
            "zip": "70239",
            "product_price": "295000"
        },
        {
            "order_id": "14805155",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Robin",
            "phone": "6.2851E+12",
            "address": "Jl.kapuk raya no.36 (seberang komplek grisenda/dealer kawasaki) Note: kirim senen-jumat  Jam 9.00-16.00",
            "province": "DKI Jakarta",
            "city": "Kota Jakarta Barat",
            "subdistrict": "Cengkareng",
            "zip": "11730",
            "product_price": "295000"
        },
        {
            "order_id": "14816336",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Nuaim Bustan/Puspawati",
            "phone": "6.28526E+12",
            "address": "Jl gatot subroto no 17 majene sulbar kantor cabang bri majene",
            "province": "Sulawesi Barat",
            "city": "Kab. Majene",
            "subdistrict": "Banggae",
            "zip": "91411",
            "product_price": "295000"
        },
        {
            "order_id": "14817525",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Imam Taufik Hidayat",
            "phone": "6.28213E+12",
            "address": "Jl. Trunojoyo Gg. VII No. 17 Kel. Pejagan Kec./Kab. Bangkalan",
            "province": "Jawa Timur",
            "city": "Kab. Bangkalan",
            "subdistrict": "Bangkalan",
            "zip": "69112",
            "product_price": "295000"
        },
        {
            "order_id": "14822594",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Rudi eko susanto",
            "phone": "6.28219E+12",
            "address": "Ds. Grinting RT 20 RW 05",
            "province": "Jawa Timur",
            "city": "Kab. Sidoarjo",
            "subdistrict": "Tulangan",
            "zip": "61273",
            "product_price": "295000"
        },
        {
            "order_id": "14841438",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Herawanto",
            "phone": "6.28534E+12",
            "address": "Tidung 9 STP 21 no.255",
            "province": "Sulawesi Selatan",
            "city": "Kota Makassar",
            "subdistrict": "Rappocini",
            "zip": "90222",
            "product_price": "295000"
        },
        {
            "order_id": "14850381",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Surian Syah",
            "phone": "6.28225E+12",
            "address": "Jl. Dr Sutomo blok.b Rt. 09. Desa Tani bakti, kec. Samboja,",
            "province": "Kalimantan Timur",
            "city": "Kab. Kutai Kartanegara",
            "subdistrict": "Samboja (Semboja)",
            "zip": "75274",
            "product_price": "295000"
        },
        {
            "order_id": "14855282",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Teguh yono slamet",
            "phone": "6.28133E+12",
            "address": "DS:belahan tengah,DSN:jurangsari(RT23) (RW09) JLN: tribuana tungga dewi  KCM:mojosari  KAB: mojokerto Jawatimur Kode pos:61382",
            "province": "Jawa Timur",
            "city": "Kab. Mojokerto",
            "subdistrict": "Mojosari",
            "zip": "61382",
            "product_price": "295000"
        },
        {
            "order_id": "14855715",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Danang",
            "phone": "6.2819E+12",
            "address": "DINDIKBUD KAB.PEMALANG  JL. MERBABU NO 2 PEMALANG",
            "province": "Jawa Tengah",
            "city": "Kab. Pemalang",
            "subdistrict": "Pemalang",
            "zip": "52319",
            "product_price": "295000"
        },
        {
            "order_id": "14857903",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Ahmad Irgie. SE",
            "phone": "6.28582E+12",
            "address": "Jl. Muso Bin Salim no .16 RT. 26 Kelurahan Melayu Kecamatan Tenggarong Kabupaten Kutai Kartanegara Kaltim post. 75511 Depan kantor Disbunhut . Kab  Kukar..",
            "province": "Kalimantan Timur",
            "city": "Kab. Kutai Kartanegara",
            "subdistrict": "Tenggarong",
            "zip": "75511",
            "product_price": "295000"
        },
        {
            "order_id": "14859865",
            "product": " (Hitam - Biru Muda) (x1) (Hitam - Orange) (x1)",
            "name": "Ratno Effendy Waray",
            "phone": "6.28124E+12",
            "address": "Sat polair polresta Balikpapan samping Polsek kawasan pelabuhan Semayang Balikpapan jln.Yoes Sudarso no.89 76111",
            "province": "Kalimantan Timur",
            "city": "Kota Balikpapan",
            "subdistrict": "Balikpapan Kota",
            "zip": "76114",
            "product_price": "590000"
        },
        {
            "order_id": "14872042",
            "product": " (Hitam - Biru Muda) (x1)",
            "name": "Deby Eka Putri",
            "phone": "6.28787E+12",
            "address": "Serdang taman Krakatau blok j1 no 1.rt/RW 003/002 kel margatani",
            "province": "Banten",
            "city": "Kab. Serang",
            "subdistrict": "Kramatwatu",
            "zip": "42161",
            "product_price": "590000"
        },
        {
            "order_id": "14881136",
            "product": " (Hitam - Biru Muda) (x1)",
            "name": "susan manise",
            "phone": "6.28129E+12",
            "address": "Jl .Depsos raya Pesanggrahan veteran Bintaro RT 3 RW 1 No 2. C belakang diva karoke.",
            "province": "DKI Jakarta",
            "city": "Kota Jakarta Selatan",
            "subdistrict": "Kebayoran Lama",
            "zip": "12230",
            "product_price": "295000"
        },
        {
            "order_id": "14881924",
            "product": " (Hitam - Biru Muda) (x1)",
            "name": "Sadirin",
            "phone": "62811569200",
            "address": "Jalan danau sentarum komp. Green silva nomor a22",
            "province": "Kalimantan Barat",
            "city": "Kota Pontianak",
            "subdistrict": "Pontianak Kota",
            "zip": "78117",
            "product_price": "295000"
        },
        {
            "order_id": "14882309",
            "product": " (Hitam - Biru Tua) (x1) (Hitam - Orange) (x1)",
            "name": "Muh. Sidiq",
            "phone": "6.28114E+11",
            "address": "Jl. Prof. Muh. Yamin No. 89. Komp. BPTP Sultra",
            "province": "Sulawesi Tenggara",
            "city": "Kota Kendari",
            "subdistrict": "Puuwatu",
            "zip": "93115",
            "product_price": "590000"
        },
        {
            "order_id": "14896795",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "David wijayanto",
            "phone": "6.28224E+12",
            "address": "Jalan pemuda boja no 17 Bri kcp boja Kelurahan boja Kecamatan boja 51381",
            "province": "Jawa Tengah",
            "city": "Kab. Kendal",
            "subdistrict": "Boja",
            "zip": "51381",
            "product_price": "295000"
        },
        {
            "order_id": "14897389",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Henri",
            "phone": "6.28181E+12",
            "address": "GOR 88 ..Kmp  Cikaret Rt 04/06 Kelurahan Harapan Jaya",
            "province": "Jawa Barat",
            "city": "Kab. Bogor",
            "subdistrict": "Cibinong",
            "zip": "16911",
            "product_price": "295000"
        },
        {
            "order_id": "14898671",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Dani saputra",
            "phone": "6.2813E+12",
            "address": "Grand Nusa indah  blok M 15 no 10 Cileungsi Bogor Jawa barat",
            "province": "Jawa Barat",
            "city": "Kab. Bogor",
            "subdistrict": "Cileungsi",
            "zip": "16820",
            "product_price": "295000"
        },
        {
            "order_id": "14904885",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "glayton yan hadibrata",
            "phone": "6.28129E+12",
            "address": "jln perkutut no 5 perum narogong indah",
            "province": "Jawa Barat",
            "city": "Kota Bekasi",
            "subdistrict": "Rawalumbu",
            "zip": "17117",
            "product_price": "590000"
        },
        {
            "order_id": "14912834",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Nurhamim ilham",
            "phone": "6.28534E+12",
            "address": "Desa Beji RT RW 02 02 sebelah barat Masjid Baiturrahman Beji Jenu Tuban Jatim",
            "province": "Jawa Timur",
            "city": "Kab. Tuban",
            "subdistrict": "Jenu",
            "zip": "62352",
            "product_price": "295000"
        },
        {
            "order_id": "14923403",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "MG Indah Wahyumukti B",
            "phone": "62818920926",
            "address": "CELEBRATION GARDEN AF.5/21, GRAND WISATA, KELURAHAN LAMBANG JAYA.",
            "province": "Jawa Barat",
            "city": "Kab. Bekasi",
            "subdistrict": "Tambun Selatan",
            "zip": "17510",
            "product_price": "295000"
        },
        {
            "order_id": "14924227",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Toto mujio muhammad",
            "phone": "6.28536E+11",
            "address": "DS.pangke RT 01/01 kec.meral.kab.karimun(Kepri,)",
            "province": "Kepulauan Riau",
            "city": "Kab. Karimun",
            "subdistrict": "Meral Barat",
            "zip": "29664",
            "product_price": "8850000"
        },
        {
            "order_id": "14927370",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Purwa agustina",
            "phone": "6.28226E+12",
            "address": "Nama purwa agustina Almt jln poros desa gandang rt 24 rw 05 kecamatan Maliku kabupaten pulang pisau provinsi kalimantan tengah kode pos 74873.",
            "province": "Kalimantan Tengah",
            "city": "Kab. Pulang Pisau",
            "subdistrict": "Kahayan Hilir",
            "zip": "74813",
            "product_price": "295000"
        },
        {
            "order_id": "14933984",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Windra",
            "phone": "6.28235E+12",
            "address": "Desa basi kecamatan Basi Dondo kabupaten Tolitoli Sulawesi tengah Jlan trans Sulawesi rumah sya pas bengkel kode pos 94552",
            "province": "Sulawesi Tengah",
            "city": "Kab. Toli-Toli",
            "subdistrict": "Basidondo",
            "zip": "94552",
            "product_price": "295000"
        },
        {
            "order_id": "15143132",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Syahrudin",
            "phone": "6.28132E+12",
            "address": "Kantor Denma Grup 3 Kopassus,  Cijantung",
            "province": "DKI Jakarta",
            "city": "Kota Jakarta Timur",
            "subdistrict": "Pasar Rebo",
            "zip": "13780",
            "product_price": "295000"
        },
        {
            "order_id": "15145185",
            "product": " (Hitam - Biru Tua) (x1)",
            "name": "Reza Mizar",
            "phone": "6.28521E+12",
            "address": "Aceh.Bireuen kota juang.jln. BMedan - B. Aceh.desa meunasah blang.dpn smp 3.komplek sdlb negeri bireuen",
            "province": "Nanggroe Aceh Darussalam (NAD)",
            "city": "Kab. Bireuen",
            "subdistrict": "Kota Juang",
            "zip": "24251",
            "product_price": "295000"
        },
        {
            "order_id": "15157608",
            "product": " (Hitam - Orange) (x1) (Hitam - Orange) (x1)",
            "name": "Gunarso",
            "phone": "6.28124E+12",
            "address": "Jlan mendawai 1 no. 92 keramat pela kebayoran baru jaksel",
            "province": "DKI Jakarta",
            "city": "Kota Jakarta Selatan",
            "subdistrict": "Kebayoran Baru",
            "zip": "12150",
            "product_price": "490000"
        },
        {
            "order_id": "15161076",
            "product": " (Hitam - Orange) (x1)",
            "name": "Erni Pujawati",
            "phone": "6.28139E+12",
            "address": "Taman Tytyan Indah Blok J1 no.1, Kali Baru, Medan Satria, Kota Bekasi",
            "province": "Jawa Barat",
            "city": "Kota Bekasi",
            "subdistrict": "Medan Satria",
            "zip": "17143",
            "product_price": "245000"
        },
        {
            "order_id": "15163158",
            "product": " (Hitam - Orange) (x1)",
            "name": "Zaenal miftah",
            "phone": "6.28132E+12",
            "address": "Jln penggilingan komp pik blok D no 48",
            "province": "DKI Jakarta",
            "city": "Kota Jakarta Timur",
            "subdistrict": "Cakung",
            "zip": "13910",
            "product_price": "245000"
        },
        {
            "order_id": "15167424",
            "product": " (Hitam - Orange) (x1)",
            "name": "Mustarin K Lasanudin",
            "phone": "6.2854E+12",
            "address": "Desa Bilungala Jalan Nicolas Caluara Kompleks KORAMIL Bonepantai",
            "province": "Gorontalo",
            "city": "Kab. Bone Bolango",
            "subdistrict": "Bonepantai",
            "zip": "96585",
            "product_price": "245000"
        },
        {
            "order_id": "15171367",
            "product": " (Hitam - Orange) (x1)",
            "name": "Juan",
            "phone": "6.28524E+12",
            "address": "Jln tasangka.no 17 Depan gereja solafide",
            "province": "Papua",
            "city": "Kota Jayapura",
            "subdistrict": "Jayapura Selatan",
            "zip": "99223",
            "product_price": "245000"
        },
        {
            "order_id": "15178857",
            "product": " (Hitam - Orange) (x1)",
            "name": "Saiful bahri",
            "phone": "6.28139E+12",
            "address": "Jln kramat Jaya gg 3 blok c no 31 Rt005/013 kel semper barat kecamatan cilincing Jakarta Utara 14130",
            "province": "DKI Jakarta",
            "city": "Kota Jakarta Utara",
            "subdistrict": "Cilincing",
            "zip": "14120",
            "product_price": "245000"
        },
        {
            "order_id": "15179204",
            "product": " (Hitam - Orange) (x1)",
            "name": "Nurseha/Ima Nurjanah",
            "phone": "6.28564E+12",
            "address": "Jalan Duwet rt 02 rw 05 Cigedog",
            "province": "Jawa Tengah",
            "city": "Kab. Brebes",
            "subdistrict": "Kersana",
            "zip": "52264",
            "product_price": "245000"
        }
    ]
}
with open('data_pembeli.json', 'w') as f:
    json.dump(rekap_pesanan, f, indent=2)